import { Repository } from 'typeorm';
import { PieceCatalogItem } from '../entities/piece-catalog-item.entity';
import { PieceCatalogCategory } from '../common/enums';

const CATALOG_SEED: Omit<PieceCatalogItem, 'id' | 'createdAt' | 'updatedAt'>[] =
  [
    // Seating
    {
      category: PieceCatalogCategory.SEATING,
      name: 'Accent Chair',
      description: 'Single upholstered or occasional chair',
      pickupFee: 85,
      storageFeeMonthly: 35,
      installFee: 95,
      sortOrder: 1,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SEATING,
      name: 'Dining Chair',
      description: 'Standard dining side chair',
      pickupFee: 45,
      storageFeeMonthly: 18,
      installFee: 55,
      sortOrder: 2,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SEATING,
      name: 'Sofa (3-Seat)',
      description: 'Standard sofa up to 90"',
      pickupFee: 195,
      storageFeeMonthly: 75,
      installFee: 225,
      sortOrder: 3,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SEATING,
      name: 'Sectional (L-Shape)',
      description: 'Large sectional, may require 2 movers',
      pickupFee: 325,
      storageFeeMonthly: 120,
      installFee: 375,
      sortOrder: 4,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SEATING,
      name: 'Ottoman / Bench',
      description: 'Ottoman, bench, or pouf',
      pickupFee: 55,
      storageFeeMonthly: 22,
      installFee: 65,
      sortOrder: 5,
      isActive: true,
    },
    // Tables
    {
      category: PieceCatalogCategory.TABLES,
      name: 'Coffee Table',
      description: 'Living room coffee table',
      pickupFee: 95,
      storageFeeMonthly: 38,
      installFee: 110,
      sortOrder: 10,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.TABLES,
      name: 'Side / End Table',
      description: 'Small accent table',
      pickupFee: 55,
      storageFeeMonthly: 22,
      installFee: 65,
      sortOrder: 11,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.TABLES,
      name: 'Dining Table',
      description: 'Dining table up to 8ft',
      pickupFee: 175,
      storageFeeMonthly: 65,
      installFee: 195,
      sortOrder: 12,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.TABLES,
      name: 'Dining Table (Large)',
      description: '10ft+ dining or conference table',
      pickupFee: 275,
      storageFeeMonthly: 95,
      installFee: 295,
      sortOrder: 13,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.TABLES,
      name: 'Desk',
      description: 'Executive or writing desk',
      pickupFee: 145,
      storageFeeMonthly: 55,
      installFee: 165,
      sortOrder: 14,
      isActive: true,
    },
    // Bedding
    {
      category: PieceCatalogCategory.BEDDING,
      name: 'Queen Bed Frame',
      description: 'Queen upholstered or panel bed',
      pickupFee: 195,
      storageFeeMonthly: 75,
      installFee: 225,
      sortOrder: 20,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.BEDDING,
      name: 'King / Cal King Bed',
      description: 'King or cal-king bed frame',
      pickupFee: 245,
      storageFeeMonthly: 90,
      installFee: 275,
      sortOrder: 21,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.BEDDING,
      name: 'Nightstand',
      description: 'Bedside table (single)',
      pickupFee: 55,
      storageFeeMonthly: 22,
      installFee: 65,
      sortOrder: 22,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.BEDDING,
      name: 'Dresser',
      description: '6-drawer dresser or chest',
      pickupFee: 165,
      storageFeeMonthly: 62,
      installFee: 185,
      sortOrder: 23,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.BEDDING,
      name: 'Armoire / Wardrobe',
      description: 'Tall wardrobe or armoire',
      pickupFee: 225,
      storageFeeMonthly: 85,
      installFee: 255,
      sortOrder: 24,
      isActive: true,
    },
    // Storage
    {
      category: PieceCatalogCategory.STORAGE,
      name: 'Bookcase',
      description: 'Tall bookcase or étagère',
      pickupFee: 125,
      storageFeeMonthly: 48,
      installFee: 145,
      sortOrder: 30,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.STORAGE,
      name: 'Credenza / Sideboard',
      description: 'Dining or media credenza',
      pickupFee: 175,
      storageFeeMonthly: 65,
      installFee: 195,
      sortOrder: 31,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.STORAGE,
      name: 'Console Table',
      description: 'Entry or sofa console',
      pickupFee: 95,
      storageFeeMonthly: 38,
      installFee: 110,
      sortOrder: 32,
      isActive: true,
    },
    // Lighting
    {
      category: PieceCatalogCategory.LIGHTING,
      name: 'Table Lamp',
      description: 'Table or buffet lamp',
      pickupFee: 35,
      storageFeeMonthly: 12,
      installFee: 45,
      sortOrder: 40,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.LIGHTING,
      name: 'Floor Lamp',
      description: 'Standing floor lamp',
      pickupFee: 55,
      storageFeeMonthly: 22,
      installFee: 65,
      sortOrder: 41,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.LIGHTING,
      name: 'Chandelier',
      description: 'Chandelier — crated handling',
      pickupFee: 195,
      storageFeeMonthly: 75,
      installFee: 275,
      sortOrder: 42,
      isActive: true,
    },
    // Rugs
    {
      category: PieceCatalogCategory.RUGS,
      name: 'Area Rug (Small)',
      description: 'Up to 6x9 — rolled',
      pickupFee: 65,
      storageFeeMonthly: 28,
      installFee: 85,
      sortOrder: 50,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.RUGS,
      name: 'Area Rug (Large)',
      description: '9x12 or larger — rolled',
      pickupFee: 125,
      storageFeeMonthly: 48,
      installFee: 145,
      sortOrder: 51,
      isActive: true,
    },
    // Specialty
    {
      category: PieceCatalogCategory.SPECIALTY,
      name: 'Mirror (Large)',
      description: 'Oversized mirror — crated',
      pickupFee: 145,
      storageFeeMonthly: 55,
      installFee: 175,
      sortOrder: 60,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SPECIALTY,
      name: 'Artwork (Framed)',
      description: 'Framed art or canvas — custom crate',
      pickupFee: 125,
      storageFeeMonthly: 48,
      installFee: 155,
      sortOrder: 61,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SPECIALTY,
      name: 'Freestanding Tub',
      description: 'Freestanding soaking tub',
      pickupFee: 395,
      storageFeeMonthly: 145,
      installFee: 450,
      sortOrder: 62,
      isActive: true,
    },
    {
      category: PieceCatalogCategory.SPECIALTY,
      name: 'Vanity (Double)',
      description: 'Double vanity console',
      pickupFee: 275,
      storageFeeMonthly: 95,
      installFee: 325,
      sortOrder: 63,
      isActive: true,
    },
  ];

export async function seedCatalogIfNeeded(repo: Repository<PieceCatalogItem>) {
  const count = await repo.count();
  if (count > 0) return;

  for (const item of CATALOG_SEED) {
    await repo.save(repo.create(item));
  }
}
